name: bright_minds
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  http: ^1.5.0
  image_picker: ^1.2.1
  file_picker: ^10.3.6
  file_selector: ^1.0.3
  google_fonts: ^6.3.2
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  youtube_player_flutter: ^9.0.1
  intl: ^0.19.0
  record: ^6.1.2
  path_provider: ^2.1.5
  speech_to_text: ^7.3.0
  flutter_svg: ^2.0.7
  audioplayers: ^6.0.0
  flutter_tts: ^3.6.3
  video_thumbnail: ^0.5.3
  video_player: ^2.5.1
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^31.2.3
  string_similarity: ^2.0.0
  path: ^1.9.0
  http_parser: ^4.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/story_images/
